### Request new
POST http://localhost:3003/api/v1/hedgehog/new HTTP/1.1
content-type: application/json

{
    "name": "Täää toimii 😭",
    "sex": "Female",
    "point": [50.23,10.3]
}


### Get 'em all
GET http://localhost:3003/api/v1/hedgehog HTTP/1.1
Content-Type: application/json


### Get by Id
GET http://localhost:3003/api/v1/hedgehog/2 HTTP/1.1
Content-Type: application/json
